# Generated by Django 5.1.7 on 2026-06-18 12:38

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'inn',
                    models.CharField(
                        max_length=12, unique=True, verbose_name='ИНН'
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('RUB', 'Российский рубль'),
                            ('USD', 'Доллар США'),
                            ('EUR', 'Евро'),
                            ('CNY', 'Китайский юань'),
                        ],
                        default='RUB',
                        max_length=3,
                        verbose_name='Валюта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'sku',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Артикул'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=500, verbose_name='Наименование'
                    ),
                ),
                (
                    'unit',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Ед. изм.'
                    ),
                ),
                (
                    'group',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Группа'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог товаров',
                'ordering': ['name'],
                'indexes': [
                    models.Index(
                        fields=['name'], name='core_catalo_name_e8306c_idx'
                    ),
                    models.Index(
                        fields=['group'], name='core_catalo_group_ce5a80_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                (
                    'file',
                    models.FileField(
                        upload_to=core.models.upload_path,
                        validators=[core.models.validate_excel_file],
                    ),
                ),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('uploaded', 'Файл загружен'),
                            ('processing', 'Обработка'),
                            ('completed', 'Готово'),
                            ('failed', 'Ошибка'),
                        ],
                        default='uploaded',
                        max_length=16,
                    ),
                ),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='estimates',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                (
                    'file',
                    models.FileField(
                        upload_to=core.models.upload_path,
                        validators=[core.models.validate_excel_file],
                    ),
                ),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('uploaded', 'Файл загружен'),
                            ('processing', 'Обработка'),
                            ('completed', 'Готово'),
                            ('failed', 'Ошибка'),
                        ],
                        default='uploaded',
                        max_length=16,
                    ),
                ),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                (
                    'supplier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='price_lists',
                        to='core.supplier',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('row_number', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                (
                    'quantity',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=16, null=True
                    ),
                ),
                (
                    'material_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    'installation_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    'match_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидает сопоставления'),
                            ('matched', 'Сопоставлено'),
                            ('no_match', 'Без соответствия'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                (
                    'match_confidence',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    'match_explanation',
                    models.CharField(blank=True, max_length=500),
                ),
                ('matched_automatically', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                (
                    'catalog_product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='estimate_items',
                        to='core.catalogproduct',
                    ),
                ),
                (
                    'estimate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='core.estimate',
                    ),
                ),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [
                    models.Index(
                        fields=['match_status'],
                        name='core_estima_match_s_3c4e72_idx',
                    ),
                    models.Index(
                        fields=['sku'], name='core_estima_sku_590164_idx'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('row_number', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                (
                    'price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                (
                    'catalog_product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supplier_items',
                        to='core.catalogproduct',
                    ),
                ),
                (
                    'price_list',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='core.pricelist',
                    ),
                ),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [
                    models.Index(
                        fields=['sku'], name='core_suppli_sku_6a40a8_idx'
                    ),
                    models.Index(
                        fields=['name'], name='core_suppli_name_49ad28_idx'
                    ),
                ],
            },
        ),
    ]
